[package]
name = "venti"
version = "0.1.0"
edition = "2021"

[dependencies]
llvm-sys-180 = { package = "llvm-sys", version = "180.0.0", features = [
  "prefer-static",
] }
clap = "4.5.13"
logos = "0.14.1"
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
async-std = "1.12.0"
